volumes:
  data:

services:
  landingpage:
    image: pulpocloud/landingpage:latest
    container_name: pulpo-landingpage
    volumes:
      - data:/app/pb_data
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.landingpage.rule=Host(`pulpo.cloud`)
      - traefik.http.routers.landingpage.entrypoints=websecure
      - traefik.http.routers.landingpage.tls.certresolver=letsencrypt
      - traefik.http.services.landingpage.loadbalancer.server.port=8090
    restart: unless-stopped
